[CMS-797] Add patch and script for decoupled upstream
pantheon-systems/drupal-composer-managed pull request #3
Opened 2022-07-27 15:45 UTC by jspellman814

The purpose of this PR is to generate a separate decoupled upstream, `pantheon-upstreams/decoupled-drupal-composer-managed` from this upstream. When changes are pushed to the `release` branch `deploy-decoupled-upstream.sh` runs, which applies the patch file to this upstream and pushes the updates to the decoupled upstream. The patch file was generated by running `git diff` from a clone of `pantheon-systems/decoupled-drupal-composer-managed` against the `release` branch of this repository. 

Additionally, this PR also introduces automation to [check the patch](https://github.com/pantheon-systems/drupal-composer-managed/pull/3/files#diff-5d1aa07e3e563cad411d67a0ff9556185b89d69c0ceccf66a660798555fa7db4) against any potential changes to this repo. A failure indicates a compatibility issue with the new changes and the patch, and would need to be resolved before merging.

This approach will keep these two projects mostly in sync, however, in the future the decoupled upstream might diverge far enough from this upstream to the point that it would make sense for there to be a completely separate upstream.

2022-07-29 17:36 UTC, jspellman814 commented on config/decoupled.patch
> ++        "enable-patching": true
This is in both, can remove this diff.

2022-07-29 17:37 UTC, jspellman814 commented on config/decoupled.patch
> ++        "drupal/pantheon_decoupled_umami_demo": "^1.0@alpha"
Suggest instead of `require`?

2022-08-01 15:20 UTC, jazzsequence commented on config/decoupled.patch
> ++        "drupal/pantheon_decoupled_umami_demo": "^1.0@alpha"
The `@alpha` is unnecessary if your `minimum-stability` is set to support pre-release versions. Since you're setting that to `alpha`, both `require`s will pull down that version automatically (assuming they're released as something like `1.0-alpha`).

2022-08-01 15:21 UTC, jazzsequence commented on config/decoupled.patch
> ++        "drupal/pantheon_decoupled_umami_demo": "^1.0@alpha"
(Obviously, if you do a `suggest` here, instead, you don't need the version.)

2022-08-02 15:51 UTC, backlineint requested changes
I also think some small modifications to the readme would be helpful to make this clear how this is different from the default upstream. The SDK team can create a follow up issue to contribute this.

2022-08-02 15:51 UTC, backlineint commented on config/decoupled.patch
> ++    "suggest": {
@jspellman814 the end result of this will be that `pantheon_decoupled_umami_demo` won't be installed as a dependency unless someone requires it manually, correct? That will prevent users from being able to use this upstream in the dashboard to create a demo backend with example content. That is currently an important use case, especially as people experiment in EA. 

I'd like to see this moved back to require. It will have an impact on simplifying EA onboarding, and doesn't actually add any other dependencies beyond what pantheon_decoupled_profile already does. If using this demo profile becomes less common we could move it to suggest at that point.

2022-08-02 15:51 UTC, backlineint commented on config/decoupled.patch
> ++        "drupal/pantheon_decoupled_profile": "^1.0"
I recall @greg-1-anderson saying that these dependencies would be better in the root composer.json than the upstream config. Open to that change if it is still the preferred approach.

2022-08-02 16:28 UTC, greg-1-anderson commented on config/decoupled.patch
> ++        "drupal/pantheon_decoupled_profile": "^1.0"
Yes, I would move this to the top-level composer.json file as well.

2022-08-02 16:33 UTC, greg-1-anderson commented on config/decoupled.patch
> ++    "suggest": {
Putting this in `suggest` in the upstream composer.json has no effect at all; I suggested putting it in the top-level composer.json file `suggest` section. I'm also okay with having it in the `require` section, since it didn't seem necessary to have a Demo profile in "real" backend sites. I would be inclined to make a separate "demo" upstream to satisfy that use case. It doesn't hurt too much to have the demo in the top-level composer.json, though, if that's the desire. Folks can always remove it from their site if they wish.

2022-08-02 17:17 UTC, jspellman814 commented on config/decoupled.patch
> ++    "suggest": {
Moved `pantheon_decoupled_umami_demo` back to `require` in the to root composer.json in [5b84129](https://github.com/pantheon-systems/drupal-composer-managed/pull/3/commits/5b8412976686acf824a619623526bac00b8917e1).

2022-08-02 17:17 UTC, jspellman814 commented on config/decoupled.patch
> ++        "drupal/pantheon_decoupled_profile": "^1.0"
Moved to root composer.json in [5b84129](https://github.com/pantheon-systems/drupal-composer-managed/pull/3/commits/5b8412976686acf824a619623526bac00b8917e1).

2022-08-02 17:26 UTC, backlineint approved these changes

2022-08-02 18:18 UTC, jspellman814 commented
Tested the script out [here](https://app.circleci.com/pipelines/github/pantheon-systems/drupal-composer-managed/35/workflows/a0d801db-9d19-49b9-af7f-98a932925bdd/jobs/52)

2022-08-09 20:22 UTC, backlineint requested changes

2022-08-09 20:22 UTC, backlineint commented on config/decoupledpatch.sh
> +$SED -i'' 's#"minimum-stability": "stable"#"minimum-stability": "alpha"#g' ../composer.json
One thing that seemed to drop out of the previous patch is the following line from the `extra` section of composer.json

```
"enable-patching": true
```

2022-08-09 22:04 UTC, greg-1-anderson commented on config/decoupledpatch.sh
> +$SED -i'' 's#"minimum-stability": "stable"#"minimum-stability": "alpha"#g' ../composer.json
Looks like it's true in the source upstream:

https://github.com/pantheon-systems/drupal-composer-managed/blob/default/composer.json#L60

2022-08-09 22:11 UTC, backlineint commented on config/decoupledpatch.sh
> +$SED -i'' 's#"minimum-stability": "stable"#"minimum-stability": "alpha"#g' ../composer.json
Ok - maybe that comment is premature then, but the reason I raised it is because I noticed that it is being dropped somewhere along the way when the code gets pushed to https://github.com/pantheon-upstreams/decoupled-drupal-composer-managed/blob/main/composer.json

2022-08-10 18:19 UTC, greg-1-anderson commented on config/decoupledpatch.sh
> +$SED -i'' 's#"minimum-stability": "stable"#"minimum-stability": "alpha"#g' ../composer.json
@jspellman814 Could you look into why this is? Maybe an earlier version of the script had this problem; I don't see how the existing script would drop this directive. Maybe add a test that checks for enable-patching in the derived repo?

Also, if you move this script to somewhere inside the .circleci directory, then the check-commits test should pass.

2022-08-10 18:20 UTC, greg-1-anderson commented on config/decoupledpatch.sh
> +$SED -i'' 's#"minimum-stability": "stable"#"minimum-stability": "alpha"#g' ../composer.json
devops/scripts would be a location more consistent with existing usage.

2022-08-10 18:27 UTC, jspellman814 commented on config/decoupledpatch.sh
> +$SED -i'' 's#"minimum-stability": "stable"#"minimum-stability": "alpha"#g' ../composer.json
@rwagner00 For your awareness too

2022-08-11 18:03 UTC, jspellman814 commented on devops/scripts/deploy-decoupled-upstream.sh
> +echo "Applying decoupled.patch"
```suggestion
echo "Executing decoupled.patch"
```

2022-08-11 18:05 UTC, jspellman814 commented on .circleci/config.yml
> +          name: Apply patch and copy commits to decoupled destination repo
```suggestion
          name: Run decoupledpatch.sh and copy commits to decoupled destination repo
```

2022-08-11 20:02 UTC, greg-1-anderson commented
Looks like you're going to need to squash these commits in order for check-commits to pass.

2022-08-11 20:04 UTC, greg-1-anderson commented on devops/scripts/deploy-decoupled-upstream.sh
> +git checkout ${CIRCLE_BRANCH} -- devops/scripts/decoupledpatch.sh
OR, you could just copy this file to a temp location BEFORE you switch branches, as that script is sitting right next to this script until you do that. Probably more straightforward than this.

2022-08-11 21:09 UTC, rwagner00 commented on devops/scripts/deploy-decoupled-upstream.sh
> +git checkout ${CIRCLE_BRANCH} -- devops/scripts/decoupledpatch.sh
Changed

2022-08-12 17:31 UTC, greg-1-anderson approved these changes
LGTM

2022-08-12 17:31 UTC, greg-1-anderson commented
The front-end sites team can submit follow-on PRs to refine the README content & etc.

2022-08-12 17:43 UTC, merged